# <u>**Importing libraries**</u>

In [15]:
import pandas as pd
import numpy as np
import statistics as st

In [16]:
chronic_diseases = pd.read_csv('chronic_disease.csv')

## <u>**a. What are the types of varibles in the dataset?**</u>

In [17]:
chronic_diseases.head(15)

,Patient_Number,BP_Abnormality,Female,Level_of_Hemoglobin,Age,BMI,Smoking,Steps_Walk_Week,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
0,1,1,1,11.28,34,23,0,45961,1,1
1,2,0,1,9.75,54,33,0,26106,0,0
2,3,1,0,10.79,70,49,0,9995,1,0
3,4,0,0,11.00,71,50,0,10635,1,0
4,5,1,0,14.17,52,19,0,15619,0,0
5,6,0,0,11.64,23,48,1,27042,0,0
6,7,1,1,11.69,43,41,0,38369,1,1
7,8,0,0,12.70,48,20,0,29781,0,0
8,9,0,0,10.88,72,44,0,814,0,0
9,10,1,0,14.56,40,44,0,1278,0,0
10,11,1,1,8.58,70,28,0,48527,1,1
11,12,1,0,12.77,35,17,0,22500,1,0
12,13,1,0,16.40,31,50,1,25639,0,1
13,14,0,0,16.42,75,40,1,11750,0,1
14,15,0,0,11.97,18,32,0,14562,1,1

In [18]:
chronic_diseases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Patient_Number                 2000 non-null   int64
 1   BP_Abnormality                 2000 non-null   int64
 2   Female                         2000 non-null   int64
 3   Level_of_Hemoglobin            2000 non-null   float64
 4   Age                            2000 non-null   int64
 5   BMI                            2000 non-null   int64
 6   Smoking                        2000 non-null   int64
 7   Steps_Walk_Week                2000 non-null   int64
 8   Chronic_kidney_disease         2000 non-null   int64
 9   Adrenal_and_thyroid_disorders  2000 non-null   int64
dtypes: float64(1), int64(9)
memory usage: 156.4 KB

In [19]:
chronic_diseases.tail(15)

,Patient_Number,BP_Abnormality,Female,Level_of_Hemoglobin,Age,BMI,Smoking,Steps_Walk_Week,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
1985,1986,0,0,10.44,38,31,0,6109,0,0
1986,1987,1,1,13.63,49,36,0,49302,1,1
1987,1988,1,0,11.79,19,44,0,35633,0,1
1988,1989,1,0,17.17,20,48,0,33663,1,0
1989,1990,1,0,10.84,20,15,0,1162,1,0
1990,1991,1,0,11.21,63,25,1,32903,0,0
1991,1992,1,0,15.53,22,24,0,48325,1,1
1992,1993,1,1,9.38,60,39,1,46591,1,1
1993,1994,0,1,9.69,73,42,1,43344,0,1
1994,1995,0,1,11.07,58,31,0,38603,0,0
1995,1996,1,1,10.14,69,26,1,26118,1,0
1996,1997,1,1,11.77,24,45,1,2572,1,1
1997,1998,1,0,16.91,18,42,0,14933,1,1
1998,1999,0,1,11.15,46,45,1,18157,0,1
1999,2000,1,0,11.36,41,45,0,20729,1,0

The **chronic_disease** dataset is a combination of unique, categorical and numerical variables, their explanation is given below:

**1. Patient_Number: A unique identifier for

In [20]:
chronic_diseases.groupby('Female')['BMI'].describe()

         count       mean        std   min   25%   50%   75%   max
Female
0       1008.0  29.962302  11.795534  10.0  20.0  30.0  40.0  50.0
1        992.0  30.202621  11.730934  10.0  20.0  30.0  40.0  50.0

In [21]:
chronic_diseases.groupby('Female')['BMI'].skew()

Female
0   -0.002300
1   -0.033004
Name: BMI, dtype: float64

In [24]:
chronic_diseases.groupby('Female')['BMI'].apply(pd.Series.kurt)

Female
0   -1.207777
1   -1.155743
Name: BMI, dtype: float64

In [25]:
chronic_diseases.groupby('Female').mean(['Patient_Number'])

,Patient_Number,BP_Abnormality,Level_of_Hemoglobin,Age,BMI,Smoking,Steps_Walk_Week,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
Female,,,,,,,,,
0,987.043651,0.466270,12.605565,45.575397,29.962302,0.509921,25166.897817,0.492063,0.449405
1,1014.173387,0.521169,10.800060,47.557460,30.202621,0.509073,25343.362903,0.518145,0.437500