In [1]:
import pandas as pd
import numpy as np
import statistics as st

In [2]:
chronic_disease = pd.read_csv('chronic_disease.csv')

In [4]:
chronic_disease.head(10)

,Patient_Number,BP_Abnormality,Female,Level_of_Hemoglobin,Age,BMI,Smoking,Steps_Walk_Week,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
0,1,1,1,11.28,34,23,0,45961,1,1
1,2,0,1,9.75,54,33,0,26106,0,0
2,3,1,0,10.79,70,49,0,9995,1,0
3,4,0,0,11.00,71,50,0,10635,1,0
4,5,1,0,14.17,52,19,0,15619,0,0
5,6,0,0,11.64,23,48,1,27042,0,0
6,7,1,1,11.69,43,41,0,38369,1,1
7,8,0,0,12.70,48,20,0,29781,0,0
8,9,0,0,10.88,72,44,0,814,0,0
9,10,1,0,14.56,40,44,0,1278,0,0

In [5]:
chronic_disease.tail(10)

,Patient_Number,BP_Abnormality,Female,Level_of_Hemoglobin,Age,BMI,Smoking,Steps_Walk_Week,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
1990,1991,1,0,11.21,63,25,1,32903,0,0
1991,1992,1,0,15.53,22,24,0,48325,1,1
1992,1993,1,1,9.38,60,39,1,46591,1,1
1993,1994,0,1,9.69,73,42,1,43344,0,1
1994,1995,0,1,11.07,58,31,0,38603,0,0
1995,1996,1,1,10.14,69,26,1,26118,1,0
1996,1997,1,1,11.77,24,45,1,2572,1,1
1997,1998,1,0,16.91,18,42,0,14933,1,1
1998,1999,0,1,11.15,46,45,1,18157,0,1
1999,2000,1,0,11.36,41,45,0,20729,1,0

In [6]:
chronic_disease.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Patient_Number                 2000 non-null   int64
 1   BP_Abnormality                 2000 non-null   int64
 2   Female                         2000 non-null   int64
 3   Level_of_Hemoglobin            2000 non-null   float64
 4   Age                            2000 non-null   int64
 5   BMI                            2000 non-null   int64
 6   Smoking                        2000 non-null   int64
 7   Steps_Walk_Week                2000 non-null   int64
 8   Chronic_kidney_disease         2000 non-null   int64
 9   Adrenal_and_thyroid_disorders  2000 non-null   int64
dtypes: float64(1), int64(9)
memory usage: 156.4 KB

In [7]:
chronic_disease.describe()

,Patient_Number,BP_Abnormality,Female,Level_of_Hemoglobin,Age,BMI,Smoking,Steps_Walk_Week,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.0000,2000.000000
mean,1000.500000,0.493500,0.496000,11.710035,46.558500,30.081500,0.509500,25254.424500,0.5050,0.443500
std,577.494589,0.500083,0.500109,2.186701,17.107832,11.761208,0.500035,14015.439623,0.5001,0.496922
min,1.000000,0.000000,0.000000,8.100000,18.000000,10.000000,0.000000,628.000000,0.0000,0.000000
25%,500.750000,0.000000,0.000000,10.147500,32.000000,20.000000,0.000000,13605.750000,0.0000,0.000000
50%,1000.500000,0.000000,0.000000,11.330000,46.000000,30.000000,1.000000,25353.000000,1.0000,0.000000
75%,1500.250000,1.000000,1.000000,12.945000,62.000000,40.000000,1.000000,37382.250000,1.0000,1.000000
max,2000.000000,1.000000,1.000000,17.560000,75.000000,50.000000,1.000000,49980.000000,1.0000,1.000000

In [13]:
chronic_disease.groupby('Female').mean(['Patient_Number']).round(2)

,Patient_Number,BP_Abnormality,Level_of_Hemoglobin,Age,BMI,Smoking,Steps_Walk_Week,Chronic_kidney_disease,Adrenal_and_thyroid_disorders
Female,,,,,,,,,
0,987.04,0.47,12.61,45.58,29.96,0.51,25166.90,0.49,0.45
1,1014.17,0.52,10.80,47.56,30.20,0.51,25343.36,0.52,0.44