In [1]:
import pandas as pd
import numpy as np
import statistics as st

In [3]:
cars = pd.read_csv('cars.csv')

In [4]:
cars

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,36945,33337,3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,23820,21761,2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,26990,24647,2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,33195,30299,3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,43755,39014,3.5,6.0,225,18,24,3880,115,197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,40565,38203,2.4,5.0,197,21,28,3450,105,186
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,42565,40083,2.3,5.0,242,20,26,3450,105,186
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,45210,42573,2.9,6.0,268,19,26,3653,110,190
426,Volvo,V40,Wagon,Europe,Front,26135,24641,1.9,4.0,170,22,29,2822,101,180
427,Volvo,XC70,Wagon,Europe,All,35145,33112,2.5,5.0,208,20,27,3823,109,186

In [5]:
cars.describe(include=[np.number], percentiles = [.01, .05, .10, .25, .5, .75, .9, .95, .99]).T

,count,mean,std,min,1%,5%,10%,25%,50%,75%,90%,95%,99%,max
MSRP,428.0,32774.855140,19431.716674,10280.0,11191.45,13691.00,15484.5,20334.250,27635.0,39205.00,52781.0,72864.25,93659.00,192465.0
Invoice,428.0,30014.700935,17642.117750,9875.0,10659.01,12836.65,14459.7,18866.000,25294.5,35710.25,48103.3,66471.95,87244.27,173560.0
EngineSize,428.0,3.196729,1.108595,1.3,1.50,1.70,1.8,2.375,3.0,3.90,4.6,5.30,6.00,8.3
Cylinders,426.0,5.807512,1.558443,3.0,4.00,4.00,4.0,4.000,6.0,6.00,8.0,8.00,9.50,12.0
Horsepower,428.0,215.885514,71.836032,73.0,103.00,115.00,130.0,165.000,210.0,255.00,302.0,338.25,469.71,500.0
MPG_City,428.0,20.060748,5.238218,10.0,12.00,14.00,15.0,17.000,19.0,21.25,26.0,29.00,35.73,60.0
MPG_Highway,428.0,26.843458,5.741201,12.0,16.27,18.00,20.0,24.000,26.0,29.00,33.3,36.00,43.73,66.0
Weight,428.0,3577.953271,758.983215,1850.0,2211.20,2513.00,2678.7,3104.000,3474.5,3977.75,4494.4,4995.45,5824.73,7190.0
Wheelbase,428.0,108.154206,8.311813,89.0,93.00,95.35,99.0,103.000,107.0,112.00,119.0,123.00,133.00,144.0
Length,428.0,186.362150,14.357991,143.0,153.27,163.00,168.0,178.000,187.0,194.00,204.0,212.00,222.00,238.0

In [8]:
cars.describe(include=[np.number]).T

,count,mean,std,min,25%,50%,75%,max
MSRP,428.0,32774.855140,19431.716674,10280.0,20334.250,27635.0,39205.00,192465.0
Invoice,428.0,30014.700935,17642.117750,9875.0,18866.000,25294.5,35710.25,173560.0
EngineSize,428.0,3.196729,1.108595,1.3,2.375,3.0,3.90,8.3
Cylinders,426.0,5.807512,1.558443,3.0,4.000,6.0,6.00,12.0
Horsepower,428.0,215.885514,71.836032,73.0,165.000,210.0,255.00,500.0
MPG_City,428.0,20.060748,5.238218,10.0,17.000,19.0,21.25,60.0
MPG_Highway,428.0,26.843458,5.741201,12.0,24.000,26.0,29.00,66.0
Weight,428.0,3577.953271,758.983215,1850.0,3104.000,3474.5,3977.75,7190.0
Wheelbase,428.0,108.154206,8.311813,89.0,103.000,107.0,112.00,144.0
Length,428.0,186.362150,14.357991,143.0,178.000,187.0,194.00,238.0

In [9]:
cars.describe(exclude=[np.number]).T

           count unique      top freq
Make         428     38   Toyota   28
Model        428    425  G35 4dr    2
Type         428      6    Sedan  262
Origin       428      3     Asia  158
DriveTrain   428      3    Front  226